#!/usr/bin/env bash
# Process and PID file
fpath="/var/run/myscript.pid"
echo $$ > /var/run/myscript.pid
    trap 'echo "I hate the kill command"; rm -rf $fpath; exit 0' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm -rf $fpath; exit 0' SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
